# Generated by Django 5.2.3 on 2025-06-23 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombreEmpleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appA.empleados'),
        ),
    ]
